name:Publish Website to Cpanel
on:
push:
branches:
- main
jobs:
name:FTP-Deploy-Action
runs-on:windows-lates
step:
-uses actions/checkout@v2.1.0
with:
fetch-depth: 2
- name: FTP-Deploy-Action
uses: SamKirkland/FTP-Deploy-Action@3.1.1
with:
ftp-server: ${{secret.FTP_SERVER}}
ftp-username: ${{secret.FTP_USERNAME}}
ftp-password: ${{secret.FTP_PASSWORD}}


